[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_build_src = yes
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
    adafruit/Adafruit GFX Library

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<game_state.cpp> +<ble_command_parser.cpp> +<display_render_logic.cpp>
